// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idnjdznpzjqhfjfetbdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlkbmpkem5wempxaGZqZmV0YmR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MjA5ODMsImV4cCI6MjA3MDE5Njk4M30.C8g9GDq4NJ0L1tRzTl7z9sQvXQi320RDyDgsJ54dbNM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});